name: GitHub Pages CI/CD

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build Gatsby site
      run: yarn build
    - name: Publish to GitHub Pages
      uses: demurgos/ga-deploy-git@v1
      with:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        srcDir: public
        destBranch: master
